FindBetweeness <- function(N,Tu,network,LogNormalized){
  
  # N and Tu are  expression data sets: we assume they have the same genes
  # network is the underlying PPI network (e.g. mouse network from biogrid)
  # graphs are created with k attributes (e.g. gibbs,close,between)
  # LogNormalized is 1 if the data has been converted to its logarithm.
  # output: 
  # a list of 2k set differences of vertices of sub-graphs generated by 
  # filtering the original graphs at the cutoff levels
  # the igraph package must be loaded
  
  require(igraph) 
  
  # delete genes that don't appear in both the expression data and the network
  # N = N[row.names(N)%in%V(network)$name,] # remove expression data for genes not in network
  Names = V(network)$name
  WhichNot = which(!(Names%in%row.names(N))) #network genes not in expression data
  # InList = Names[Names%in%row.names(N)] #we don't use this 
  network = igraph::delete.vertices(network,V(network)[WhichNot])
  
  # Remove any multiple edges
  network = igraph::simplify(network, remove.multiple=TRUE)
  
  # Remove any vertices that are not connected
  BadV = which(degree(network,V(network))==0)
  network = igraph::delete.vertices(network,BadV)
  
  # Remove these from the expression data
  N = N[row.names(N)%in%V(network)$name,]
  Tu = Tu[row.names(Tu)%in%V(network)$name,]
  
  # reorder expression levels to match vertex order
  J=c()
  for (j in 1:length(V(network)$name)){
    J[j] = which(row.names(N) == V(network)$name[j])
  }
  N=N[J,]
  Tu=Tu[J,]
  
  # find correlations 
  NormExpr = t(N) # transpose matrix N
  
  normalg = network
  
  if (LogNormalized == 0){
    NAbs = colSums(abs(NormExpr))
    if (min(NAbs) == 0){
      I = which(NAbs == 0)
      NormExpr = NormExpr[,-I] # remove columns with all zeros [NOTE: these columns correspond to genes]
      normalg = delete.vertices(normalg,I) # remove the corresponding vertices from the graph
    }
  }
  if (LogNormalized != 0){
    NormExpr = log2(NormExpr) 
    m = min(NormExpr)
    M = max(NormExpr)
    NormExpr = 1/(M-m)*(NormExpr-m)
  }
  
  NCorP = cor(NormExpr, method = "pearson")
  NCorS = cor(NormExpr, method = "spearman")
  
  NCor = pmin(NCorP, NCorS) # take smaller of the two correlations
  
  DistNorm = 1-abs(NCor)
  I = DistNorm[is.na(DistNorm)] = 1 # replace NAs with a distance of 1
  m = min(DistNorm[DistNorm != 0])  # replace zeros with the smallest non-zero value
  DistNorm[DistNorm == 0] = m
  
  
  
  TumorExpr = t(Tu)
  tumorg = network
  if (LogNormalized == 0){
    TAbs = colSums(abs(TumorExpr))
    if (min(TAbs) == 0){
      I = which(TAbs == 0)
      TumorExpr = TumorExpr[,-I]
      tumorg = delete.vertices(tumorg,I)
    }
  }
  if (LogNormalized != 0){
    TumorExpr = log2(TumorExpr) 
    m = min(TumorExpr)
    M = max(TumorExpr)
    TumorExpr = 1/(M-m)*(TumorExpr-m)
  }
  
  TCorP = cor(TumorExpr, method = "pearson")
  TCorS = cor(TumorExpr, method = "spearman")
  
  TCor = pmin(TCorP, TCorS) # take smaller of the two correlations
    
  DistTumor = 1-abs(TCor)
  I = DistTumor[is.na(DistTumor)] = 1 # replace NAs with a distance of 1
  m_tumor = min(DistTumor[DistTumor != 0])  # replace zeros with the smallest non-zero value
  DistTumor[DistTumor == 0] = m_tumor
  
  
  # make two new graphs with edge weights ("distances") based on correlations: 
  # one for the normal data
  norm_adj <- get.adjacency(normalg, type = c("both"), attr = NULL, edges = FALSE, names = TRUE)
  
  norm_adj = norm_adj*DistNorm
  
  normalg = graph.adjacency(norm_adj, mode = c("undirected"), weighted = TRUE, diag = TRUE) #igraph object from adjacency matrix
  
  
  
  # one for the tumor data
  tumor_adj <- get.adjacency(tumorg, type = c("both"), attr = NULL, edges = FALSE, names = TRUE)
  
  tumor_adj = tumor_adj*DistTumor
  
  tumorg = graph.adjacency(tumor_adj, mode = c("undirected"), weighted = TRUE, diag = TRUE)
  
  
  
  # Calculate complexity measures and store as vertex attributes, also set names
  V(normalg)$between = betweenness(normalg, v=V(normalg), directed = FALSE, nobigint = TRUE, normalized = FALSE)
  V(tumorg)$between = betweenness(tumorg, v=V(tumorg), directed = FALSE, nobigint = TRUE, normalized = FALSE)
  
  V(normalg)$close = closeness(normalg, v=V(normalg), mode = "all", normalized = FALSE)
  V(tumorg)$close = closeness(tumorg, v=V(tumorg), mode = "all", normalized = FALSE)
  
  # V(normalg)$deg = degree(normalg, v = V(normalg), loops = FALSE, normalized = FALSE)
  # V(tumorg)$deg = degree(tumorg, v = V(tumorg), loops = FALSE, normalized = FALSE)
  # 
  # V(normalg)$gs = graph.strength(normalg)
  # V(tumorg)$gs = graph.strength(tumorg)  
  
  
  # return elements listed below
  list(normalg = normalg, tumorg = tumorg)  
}





